#!/bin/bash
#PBS -N SpMV_first_try
#PBS -o ./SpMV_first_try.out
#PBS -e ./SpMV_first_try.err
#PBS -q short_cpuQ
#PBS -l walltime=06:00:00
#PBS -l select=1:ncpus=64:mem=32gb

module load gcc91
module load perf

cd "$ PBS_O_WORKDIR " # go to the directory where qsub was run

# Compile and run 

set -euo pipefail

# CONFIGURATION

SOURCE="../src/*.c"                 # C source file to be compiled
OUTDIR="../results"                # results and logs folder
MATRIX_DIR="../data_matrices"      # matrices folder
SEQ_BIN="seq_program"           # binary name for sequential version
PAR_BIN="par_program"           # binary name for parallel version
REPEATS=10

MATRIX_FILES=("$MATRIX_DIR"/*.mtx)

RUN_TYPES_PAR=("static" "dynamic" "guided")
CHUNK_SIZES=(1 10 100) #1000 10000
NUM_THREADS=(1 2 4 8) #16 32 64

PERF_ENABLE=${PERF_ENABLE:-false}

CC=${CC:-gcc}
PERF_CMD=$(command -v perf || true)

mkdir -p "$OUTDIR"/{bin,logs,perf}
LOGDIR="$OUTDIR/logs"
PERFDIR="$OUTDIR/perf"
BINDIR="$OUTDIR/bin"

CSV="$OUTDIR/summary.csv"
CSV_PERF="$OUTDIR/summary_perf.csv"
echo "run_type,mode,schedule,chunk,threads,repeat,metric,value,log_file" > "$CSV"
echo "run_type,mode,schedule,chunk,threads,repeat,metric,value,log_file" > "$CSV_PERF"

run_code() {
  local cmd=("$@")
  "${cmd[@]}"
}

###############################################
# COMPILE CODES
###############################################
echo "Sequential compilation (-O3)"
$CC -O3 -std=c11 -o "${BINDIR}/${SEQ_BIN}" "${SOURCE}"

echo "Parallel compilation (-O3 + OpenMP)"
$CC -O3 -fopenmp -std=c11 -o "${BINDIR}/${PAR_BIN}" "${SOURCE}"


###############################################
# RUN CODES
###############################################
for MATRIX in "${MATRIX_FILES[@]}"; do
    FILENAME=$(basename "$MATRIX")
    echo -e "\n### USING MATRIX: $FILENAME ###\n"
    
    ###############################################
    # SEQUENTIAL RUNS
    ###############################################
    echo -e "\n=== SEQUENTIAL RUNS ===\n"
    
    logf="${LOGDIR}/seq_runs.log"
    perf_logf="${PERFDIR}/seq_perf.log"
    for ((i=1;i<=REPEATS;i++)); do
        stamp=$(date +"%Y%m%d_%H%M%S")

        echo "Sequential run #$i"
        
        if [[ "$PERF_ENABLE" == false ]]; then
            start=$(date +%s.%N)
            run_code "${BINDIR}/${SEQ_BIN}" "../data_matrices/${FILENAME}"> "$logf.tmp" 2>&1 || rc=$? || rc=$?
            end=$(date +%s.%N)
            
            elapsed=$(grep -Eo 'SPMV_TIME=[0-9.]+' "$logf.tmp" | cut -d= -f2 | tail -n1)
            if [[ -z "$elapsed" ]]; then
                elapsed=$(awk -v s="$start" -v e="$end" 'BEGIN{print e - s}')
            fi

            cat "$logf.tmp" >> "$logf"
            rm -f "$logf.tmp"
            
            #echo "Run #$i time_from_program: ${elapsed}s" >> "$logf"
            echo "sequential,code,-,-,-,${i},time,${elapsed},${logf}" >> "$CSV"
        else
            # [MOD] Solo esecuzione perf
            run_code "$PERF_CMD" stat -e cache-misses,cache-references,cycles,instructions \
                -o "$perf_logf.tmp" "${BINDIR}/${SEQ_BIN}" "$MATRIX" > /dev/null 2>&1 || true

            cache_miss=$(grep "cache-misses" "$perf_logf.tmp" | awk '{print $1}' | tr -d ',')
            cache_ref=$(grep "cache-references" "$perf_logf.tmp" | awk '{print $1}' | tr -d ',')
            cycles=$(grep "cycles" "$perf_logf.tmp" | awk '{print $1}' | tr -d ',')
            instr=$(grep "instructions" "$perf_logf.tmp" | awk '{print $1}' | tr -d ',')
            echo "sequential,perf,-,-,-,${i},cache-misses,${cache_miss:-NA},${perf_logf}" >> "$CSV_PERF"
            echo "sequential,perf,-,-,-,${i},cache-references,${cache_ref:-NA},${perf_logf}" >> "$CSV_PERF"
            echo "sequential,perf,-,-,-,${i},cycles,${cycles:-NA},${perf_logf}" >> "$CSV_PERF"
            echo "sequential,perf,-,-,-,${i},instructions,${instr:-NA},${perf_logf}" >> "$CSV_PERF"
            rm -f "$perf_logf.tmp"
        fi
    done

    ###############################################
    # PARALLEL RUNS
    ###############################################
    echo -e "\n=== PARALLEL RUNS ===\n"

    logf="${LOGDIR}/par_runs.log"
    perf_logf="${PERFDIR}/par_perf.log"
    for schedule in "${RUN_TYPES_PAR[@]}"; do
        echo -e "\n--- ${schedule} scheduling ---\n"
        for chunk in "${CHUNK_SIZES[@]}"; do
            for th in "${NUM_THREADS[@]}"; do
                for ((i=1;i<=REPEATS;i++)); do
                    stamp=$(date +"%Y%m%d_%H%M%S")

                    echo "[$schedule] chunk=$chunk threads=$th run #$i"

                    if [[ "$PERF_ENABLE" == false ]]; then
                        run_code "${BINDIR}/${PAR_BIN}" "$MATRIX" "$schedule" "$chunk" "$th" > "$logf.tmp" 2>&1 || rc=$? || rc=$?
                        elapsed=$(grep -Eo 'SPMV_TIME=[0-9.]+' "$logf.tmp" | cut -d= -f2 | tail -n1)
                        if [[ -z "$elapsed" ]]; then
                            start=$(date +%s.%N)
                            run_code "${BINDIR}/${PAR_BIN}" "$MATRIX" "$schedule" "$chunk" "$th" > /dev/null 2>&1 || rc=$? || rc=$?
                            end=$(date +%s.%N)
                            elapsed=$(awk -v s="$start" -v e="$end" 'BEGIN{print e - s}')
                        fi
                        cat "$logf.tmp" >> "$logf"
                        rm -f "$logf.tmp"
                        #echo "Run #$i time_from_program: ${elapsed}s" >> "$logf"
                        echo "parallel,code,${schedule},${chunk},${th},${i},time,${elapsed},${logf}" >> "$CSV"

                    else
                        run_code "$PERF_CMD" stat -e cache-misses,cache-references,cycles,instructions \
                            -o "$perf_logf.tmp" "${BINDIR}/${PAR_BIN}" "$MATRIX" "$schedule" "$chunk" "$th" > /dev/null 2>&1 || true

                        cache_miss=$(grep "cache-misses" "$perf_logf.tmp" | awk '{print $1}' | tr -d ',')
                        cache_ref=$(grep "cache-references" "$perf_logf.tmp" | awk '{print $1}' | tr -d ',')
                        cycles=$(grep "cycles" "$perf_logf.tmp" | awk '{print $1}' | tr -d ',')
                        instr=$(grep "instructions" "$perf_logf.tmp" | awk '{print $1}' | tr -d ',')

                        echo "parallel,perf,${schedule},${chunk},${th},${i},cache-misses,${cache_miss:-NA},${perf_logf}" >> "$CSV_PERF"
                        echo "parallel,perf,${schedule},${chunk},${th},${i},cache-references,${cache_ref:-NA},${perf_logf}" >> "$CSV_PERF"
                        echo "parallel,perf,${schedule},${chunk},${th},${i},cycles,${cycles:-NA},${perf_logf}" >> "$CSV_PERF"
                        echo "parallel,perf,${schedule},${chunk},${th},${i},instructions,${instr:-NA},${perf_logf}" >> "$CSV_PERF"
                        rm -f "$perf_logf.tmp"
                    fi
                done
            done
        done
    done
done

echo -e "\n=== Runs completed ===\n"
if [[ "$PERF_ENABLE" == true ]]; then
    echo "Perf results saved to $CSV_PERF"
else
    echo "Normal results saved to $CSV"
fi
echo "Logs: $LOGDIR"
echo "Perf logs: $PERFDIR"